NewsPortal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('accounts/', include('allauth.urls')),
    path('', include('news.urls')),
]

news/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from .views import (PostList, PostDetail, PostSearch,
                    PostCreate, PostUpdate, PostDelete,
                    subscriptions, subscribe, CategoryListView)

urlpatterns = [
    path('news/', cache_page(60)(PostList.as_view()), name='posts'),
    path('news/<int:pk>', PostDetail.as_view(), name='news_detail'),
    path('news/search/', cache_page(60)(PostSearch.as_view()), name='news_search'),
    path('news/create/', PostCreate.as_view(), name='news_create'),
    path('article/create/', PostCreate.as_view(), name='article_create'),
    path('news/<int:pk>/update/', PostUpdate.as_view(), name='news_update'),
    path('article/<int:pk>/update/', PostUpdate.as_view(), name='news_update'),
    path('news/<int:pk>/delete/', PostDelete.as_view(), name='news_delete'),
    path('article/<int:pk>/delete/', PostDelete.as_view(), name='news_delete'),
    path('subscriptions/', subscriptions, name='subscriptions'),
    path('categories/<int:pk>', cache_page(60 * 5)(CategoryListView.as_view()), name='category_news'),
    path('categories/<int:pk>/subscribe', subscribe, name='subscribe'),
]

news/models.py
from django.core.cache import cache
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class Author(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
    )
    rating = models.IntegerField(default=0)

    def update_rating(self):
        post_ratings = self.post_set.aggregate(total=models.Sum(models.F('rating')*3))['total'] or 0
        comment_ratings = self.user.comment_set.aggregate(total=models.Sum('rating'))['total'] or 0
        post_comment_ratings = self.post_set.aggregate(total=models.Sum('comment__rating'))['total'] or 0
        self.author_rating = post_ratings + comment_ratings + post_comment_ratings
        self.save()

    def __str__(self):
        return self.user.username


class Category(models.Model):
    name = models.CharField(
        max_length=64,
        unique=True,
    )

    def __str__(self):
        return self.name


class Post(models.Model):
    ARTICLE = 'AR'
    NEWS = 'NW'

    POSTS = [
        (ARTICLE, 'article'),
        (NEWS, 'news')
    ]

    author = models.ForeignKey(
        to=Author,
        on_delete=models.CASCADE,
    )
    post_type = models.CharField(
        max_length=2,
        choices=POSTS,
        default='AR',
    )
    created_at = models.DateTimeField(auto_now_add=True)
    category = models.ManyToManyField(
        to=Category,
        through='PostCategory',
    )
    title = models.CharField(max_length=128)
    text = models.TextField()
    rating = models.IntegerField(default=0)

    def preview(self):
        return f'{self.text[:124]}...'

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    def __str__(self):
        return (f'{self.title.title()}:'
                f'{self.text[:24]}')

    def get_absolute_url(self):
        return reverse('news_detail', args=[str(self.id)])

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        cache.delete(f'post-{self.pk}')


class PostCategory(models.Model):
    post = models.ForeignKey(
        to=Post,
        on_delete=models.CASCADE,
    )
    category = models.ForeignKey(
        to=Category,
        on_delete=models.CASCADE,
    )


class Comment(models.Model):
    post = models.ForeignKey(
        to=Post,
        on_delete=models.CASCADE,
    )
    user = models.ForeignKey(
        to=User,
        on_delete=models.CASCADE,
    )
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    rating = models.IntegerField(default=0)


    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -=1
        self.save()


class Subscriber(models.Model):
    user = models.ForeignKey(
        to=User,
        on_delete=models.CASCADE,
        related_name='subscriptions',
    )
    category = models.ForeignKey(
        to=Category,
        on_delete=models.CASCADE,
        related_name='subscriptions',
    )

    def __str__(self):
        return f'{self.user.username} subscribed to {self.category.name}.'

templates/article.html
{% extends 'flatpages/default.html' %}

{% block title %}
Post
{% endblock title %}

{% block content %}
<h1>{{ article }}</h1>
{% endblock content %}

templates/posts.html
{% extends 'flatpages/default.html' %}
{% load custom_filters %}
{% load custom_tags %}

{% block title %}
    <p>NEWS</p>
    <p><a href="{% url 'news_search' %}">Search</a></p>
{% endblock title %}

{% block content %}
    <h1>Actual news</h1>
    <h4>Total news: {{ page_obj.paginator.count }}</h4>
    <hr>

    <h2>
        {% if perms.news.add_post %}
            <u><a href="{% url 'news_create' %}">Add news</a></u>
            <u><a href="{% url 'article_create' %}">Add article</a></u>
        {% endif %}
    </h2>
    <hr>

    {% if posts %}
    <ul>
        {% for post in posts %}
            <li>
                <h3><a href="{% url 'news_detail' post.pk %}">{{ post.title|censor }}</a></h3>
                <p><strong>Published: </strong> {{ post.created_at|date:'d.m.Y' }}</p>
                <p>{{ post.text|censor|safe|truncatewords:20 }}</p>
                <p><b>
                    {% if perms.news.change_post %}
                        <a href="{% url 'news_update' pk=post.id %}">Edit</a>
                    {% endif %}

                    {% if perms.news.delete_post %}
                        <a href="{% url 'news_delete' post.id %}">Delete</a>
                    {% endif %}
                </b></p>
            </li>
        {% endfor %}
    </ul>
    {% else %}
        <h2>No news available!</h2>
    {% endif %}

    {% if page_obj.has_previous %}
        <a href="?{% url_replace page=1 %}">1</a>
        {% if page_obj.previous_page_number != 1 %}
            ...
            <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
        {% endif %}
    {% endif %}

    {{ page_obj.number }}

    {% if page_obj.has_next %}
        <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
        {% if paginator.num_pages != page_obj.next_page_number %}
            ...
            <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
        {% endif %}
    {% endif %}

{% endblock content %}